### ISSUE TITLE
Required Fixes/Updates

### ISSUE THREAD

**Issue by Fhrozen** [Fhrozen/motion_dance#5]
- [ ] Include absolute on label #4 
- [ ] Rewrite convert_data #4 
- [ ] Rewrite motion_beat calculation
- [ ] Test force teaching and add results #4 
- [ ] Fix add_noise ValueError: low >= high
- [ ] Evaluate.py: Check and fix entropy np.nan

**Comment by Fhrozen** [comment]
#6
